# Generated by Django 4.0.4 on 2022-05-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("article", models.TextField(max_length=1000)),
                ("password", models.CharField(max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("nickname", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("comment_lev", models.PositiveSmallIntegerField(default=0)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ref_comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_comment",
                        to="board.comment",
                    ),
                ),
                (
                    "ref_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_comment",
                        to="board.board",
                    ),
                ),
            ],
        ),
    ]
