# Generated by Django 4.0.4 on 2022-05-18 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('article', models.TextField(max_length=1000)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('comment_lev', models.PositiveSmallIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_comment', to='board.comment')),
                ('ref_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='board.article')),
            ],
        ),
    ]
